ENVIRONMENT:
  DATA_BASE_DIR: '../raw_data/'

DATA_PREPARE:
  ALL_SERIES_IDS_TXT: 'file_list/labeled_series.txt'
  BAD_CASE_SERIES_IDS_TXT: None
  IMAGE_DIR: 'crop_labeled_image/'
  MASK_DIR: 'crop_labeled_mask/'
  IMAGE_SUFFIX: '.nii.gz'
  MASK_SUFFIX: '.nii.gz'
  TRAIN_SERIES_IDS_TXT: None
  VAL_SERIES_IDS_TXT: None
  OUT_DIR: '../gen_data/full_crop_train/'
  COARSE_MASK_LABEL: 13
  FINE_MASK_LABEL: 13
  PART_LABEL: [7, 8, 9, 10, 12]
  EXTEND_SIZE: 40
  VAL_RATIO: 0.2
  WINDOW_LEVEL: [-500, 500]
  OUT_COARSE_SIZE: [176, 212, 212]
  OUT_FINE_SIZE: [176, 212, 212]
  OUT_PART_SIZE: [176, 212, 212]
  IS_SPLIT_5FOLD: False